# Generated by Django 5.2 on 2025-04-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='estado',
        ),
        migrations.AddField(
            model_name='lectura',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('oxigeno', 'Oxígeno')], default='temperatura', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
