# mqtt/docker-compose.yml
version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-config:/mosquitto/config
      - mosquitto-logs:/mosquitto/log

volumes:
  mosquitto-data:
  mosquitto-config:
  mosquitto-logs:
