services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=arquitectura_cluster
      - CASSANDRA_START_RPC=true
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

volumes:
  cassandra-data:
